#!/usr/bin/env bash
python $1 > $2

DIR=`pwd`

emacs -Q --batch \
--eval "(progn
     (setq make-backup-files nil)
     (require 'org)(require 'org-table)
     (mapc (lambda (file)
            (find-file (expand-file-name file \"$DIR\"))
            (org-table-map-tables 'org-table-align)
            (write-file file nil)
            (org-html-export-to-html)
            (kill-buffer)) '(\"$2\")))"
